// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("WebGit .NET")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("John Gietzen")]
[assembly: AssemblyProduct("WebGit .NET")]
[assembly: AssemblyCopyright("Copyright © John Gietzen 2011")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: ComVisible(false)]

[assembly: Guid("c7b5234b-4e35-4791-b359-c59152302fb8")]

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
