// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("WebGit .NET Repo Impact Plugin")]
[assembly: Guid("30e290e3-4966-4432-82c7-efb07574b20b")]
