// <auto-generated />
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("WebGit .NET Standard Search Providers")]
[assembly: Guid("8639569f-e990-4726-9d70-2f67a9a0cc64")]
